// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pkg/apiclient/rollout/rollout.proto

package rollout

import (
	context "context"
	v1alpha1 "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolloutService_GetRolloutInfo_FullMethodName    = "/rollout.RolloutService/GetRolloutInfo"
	RolloutService_WatchRolloutInfo_FullMethodName  = "/rollout.RolloutService/WatchRolloutInfo"
	RolloutService_ListRolloutInfos_FullMethodName  = "/rollout.RolloutService/ListRolloutInfos"
	RolloutService_WatchRolloutInfos_FullMethodName = "/rollout.RolloutService/WatchRolloutInfos"
	RolloutService_GetNamespace_FullMethodName      = "/rollout.RolloutService/GetNamespace"
	RolloutService_RestartRollout_FullMethodName    = "/rollout.RolloutService/RestartRollout"
	RolloutService_PromoteRollout_FullMethodName    = "/rollout.RolloutService/PromoteRollout"
	RolloutService_AbortRollout_FullMethodName      = "/rollout.RolloutService/AbortRollout"
	RolloutService_SetRolloutImage_FullMethodName   = "/rollout.RolloutService/SetRolloutImage"
	RolloutService_UndoRollout_FullMethodName       = "/rollout.RolloutService/UndoRollout"
	RolloutService_RetryRollout_FullMethodName      = "/rollout.RolloutService/RetryRollout"
	RolloutService_Version_FullMethodName           = "/rollout.RolloutService/Version"
)

// RolloutServiceClient is the client API for RolloutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RolloutServiceClient interface {
	GetRolloutInfo(ctx context.Context, in *RolloutInfoQuery, opts ...grpc.CallOption) (*RolloutInfo, error)
	WatchRolloutInfo(ctx context.Context, in *RolloutInfoQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RolloutInfo], error)
	ListRolloutInfos(ctx context.Context, in *RolloutInfoListQuery, opts ...grpc.CallOption) (*RolloutInfoList, error)
	WatchRolloutInfos(ctx context.Context, in *RolloutInfoListQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RolloutWatchEvent], error)
	GetNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NamespaceInfo, error)
	RestartRollout(ctx context.Context, in *RestartRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error)
	PromoteRollout(ctx context.Context, in *PromoteRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error)
	AbortRollout(ctx context.Context, in *AbortRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error)
	SetRolloutImage(ctx context.Context, in *SetImageRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error)
	UndoRollout(ctx context.Context, in *UndoRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error)
	RetryRollout(ctx context.Context, in *RetryRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error)
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionInfo, error)
}

type rolloutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolloutServiceClient(cc grpc.ClientConnInterface) RolloutServiceClient {
	return &rolloutServiceClient{cc}
}

func (c *rolloutServiceClient) GetRolloutInfo(ctx context.Context, in *RolloutInfoQuery, opts ...grpc.CallOption) (*RolloutInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloutInfo)
	err := c.cc.Invoke(ctx, RolloutService_GetRolloutInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) WatchRolloutInfo(ctx context.Context, in *RolloutInfoQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RolloutInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RolloutService_ServiceDesc.Streams[0], RolloutService_WatchRolloutInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RolloutInfoQuery, RolloutInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RolloutService_WatchRolloutInfoClient = grpc.ServerStreamingClient[RolloutInfo]

func (c *rolloutServiceClient) ListRolloutInfos(ctx context.Context, in *RolloutInfoListQuery, opts ...grpc.CallOption) (*RolloutInfoList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloutInfoList)
	err := c.cc.Invoke(ctx, RolloutService_ListRolloutInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) WatchRolloutInfos(ctx context.Context, in *RolloutInfoListQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RolloutWatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RolloutService_ServiceDesc.Streams[1], RolloutService_WatchRolloutInfos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RolloutInfoListQuery, RolloutWatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RolloutService_WatchRolloutInfosClient = grpc.ServerStreamingClient[RolloutWatchEvent]

func (c *rolloutServiceClient) GetNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NamespaceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceInfo)
	err := c.cc.Invoke(ctx, RolloutService_GetNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) RestartRollout(ctx context.Context, in *RestartRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha1.Rollout)
	err := c.cc.Invoke(ctx, RolloutService_RestartRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) PromoteRollout(ctx context.Context, in *PromoteRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha1.Rollout)
	err := c.cc.Invoke(ctx, RolloutService_PromoteRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) AbortRollout(ctx context.Context, in *AbortRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha1.Rollout)
	err := c.cc.Invoke(ctx, RolloutService_AbortRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) SetRolloutImage(ctx context.Context, in *SetImageRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha1.Rollout)
	err := c.cc.Invoke(ctx, RolloutService_SetRolloutImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) UndoRollout(ctx context.Context, in *UndoRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha1.Rollout)
	err := c.cc.Invoke(ctx, RolloutService_UndoRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) RetryRollout(ctx context.Context, in *RetryRolloutRequest, opts ...grpc.CallOption) (*v1alpha1.Rollout, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1alpha1.Rollout)
	err := c.cc.Invoke(ctx, RolloutService_RetryRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolloutServiceClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, RolloutService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolloutServiceServer is the server API for RolloutService service.
// All implementations must embed UnimplementedRolloutServiceServer
// for forward compatibility.
type RolloutServiceServer interface {
	GetRolloutInfo(context.Context, *RolloutInfoQuery) (*RolloutInfo, error)
	WatchRolloutInfo(*RolloutInfoQuery, grpc.ServerStreamingServer[RolloutInfo]) error
	ListRolloutInfos(context.Context, *RolloutInfoListQuery) (*RolloutInfoList, error)
	WatchRolloutInfos(*RolloutInfoListQuery, grpc.ServerStreamingServer[RolloutWatchEvent]) error
	GetNamespace(context.Context, *emptypb.Empty) (*NamespaceInfo, error)
	RestartRollout(context.Context, *RestartRolloutRequest) (*v1alpha1.Rollout, error)
	PromoteRollout(context.Context, *PromoteRolloutRequest) (*v1alpha1.Rollout, error)
	AbortRollout(context.Context, *AbortRolloutRequest) (*v1alpha1.Rollout, error)
	SetRolloutImage(context.Context, *SetImageRequest) (*v1alpha1.Rollout, error)
	UndoRollout(context.Context, *UndoRolloutRequest) (*v1alpha1.Rollout, error)
	RetryRollout(context.Context, *RetryRolloutRequest) (*v1alpha1.Rollout, error)
	Version(context.Context, *emptypb.Empty) (*VersionInfo, error)
	mustEmbedUnimplementedRolloutServiceServer()
}

// UnimplementedRolloutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolloutServiceServer struct{}

func (UnimplementedRolloutServiceServer) GetRolloutInfo(context.Context, *RolloutInfoQuery) (*RolloutInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolloutInfo not implemented")
}
func (UnimplementedRolloutServiceServer) WatchRolloutInfo(*RolloutInfoQuery, grpc.ServerStreamingServer[RolloutInfo]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRolloutInfo not implemented")
}
func (UnimplementedRolloutServiceServer) ListRolloutInfos(context.Context, *RolloutInfoListQuery) (*RolloutInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRolloutInfos not implemented")
}
func (UnimplementedRolloutServiceServer) WatchRolloutInfos(*RolloutInfoListQuery, grpc.ServerStreamingServer[RolloutWatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchRolloutInfos not implemented")
}
func (UnimplementedRolloutServiceServer) GetNamespace(context.Context, *emptypb.Empty) (*NamespaceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespace not implemented")
}
func (UnimplementedRolloutServiceServer) RestartRollout(context.Context, *RestartRolloutRequest) (*v1alpha1.Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartRollout not implemented")
}
func (UnimplementedRolloutServiceServer) PromoteRollout(context.Context, *PromoteRolloutRequest) (*v1alpha1.Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteRollout not implemented")
}
func (UnimplementedRolloutServiceServer) AbortRollout(context.Context, *AbortRolloutRequest) (*v1alpha1.Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortRollout not implemented")
}
func (UnimplementedRolloutServiceServer) SetRolloutImage(context.Context, *SetImageRequest) (*v1alpha1.Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRolloutImage not implemented")
}
func (UnimplementedRolloutServiceServer) UndoRollout(context.Context, *UndoRolloutRequest) (*v1alpha1.Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndoRollout not implemented")
}
func (UnimplementedRolloutServiceServer) RetryRollout(context.Context, *RetryRolloutRequest) (*v1alpha1.Rollout, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryRollout not implemented")
}
func (UnimplementedRolloutServiceServer) Version(context.Context, *emptypb.Empty) (*VersionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedRolloutServiceServer) mustEmbedUnimplementedRolloutServiceServer() {}
func (UnimplementedRolloutServiceServer) testEmbeddedByValue()                        {}

// UnsafeRolloutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolloutServiceServer will
// result in compilation errors.
type UnsafeRolloutServiceServer interface {
	mustEmbedUnimplementedRolloutServiceServer()
}

func RegisterRolloutServiceServer(s grpc.ServiceRegistrar, srv RolloutServiceServer) {
	// If the following call pancis, it indicates UnimplementedRolloutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolloutService_ServiceDesc, srv)
}

func _RolloutService_GetRolloutInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutInfoQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).GetRolloutInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_GetRolloutInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).GetRolloutInfo(ctx, req.(*RolloutInfoQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_WatchRolloutInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RolloutInfoQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RolloutServiceServer).WatchRolloutInfo(m, &grpc.GenericServerStream[RolloutInfoQuery, RolloutInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RolloutService_WatchRolloutInfoServer = grpc.ServerStreamingServer[RolloutInfo]

func _RolloutService_ListRolloutInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloutInfoListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).ListRolloutInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_ListRolloutInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).ListRolloutInfos(ctx, req.(*RolloutInfoListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_WatchRolloutInfos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RolloutInfoListQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RolloutServiceServer).WatchRolloutInfos(m, &grpc.GenericServerStream[RolloutInfoListQuery, RolloutWatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RolloutService_WatchRolloutInfosServer = grpc.ServerStreamingServer[RolloutWatchEvent]

func _RolloutService_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_GetNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).GetNamespace(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_RestartRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).RestartRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_RestartRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).RestartRollout(ctx, req.(*RestartRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_PromoteRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).PromoteRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_PromoteRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).PromoteRollout(ctx, req.(*PromoteRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_AbortRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).AbortRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_AbortRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).AbortRollout(ctx, req.(*AbortRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_SetRolloutImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).SetRolloutImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_SetRolloutImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).SetRolloutImage(ctx, req.(*SetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_UndoRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).UndoRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_UndoRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).UndoRollout(ctx, req.(*UndoRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_RetryRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).RetryRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_RetryRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).RetryRollout(ctx, req.(*RetryRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolloutService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolloutServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolloutService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolloutServiceServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RolloutService_ServiceDesc is the grpc.ServiceDesc for RolloutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolloutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rollout.RolloutService",
	HandlerType: (*RolloutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRolloutInfo",
			Handler:    _RolloutService_GetRolloutInfo_Handler,
		},
		{
			MethodName: "ListRolloutInfos",
			Handler:    _RolloutService_ListRolloutInfos_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _RolloutService_GetNamespace_Handler,
		},
		{
			MethodName: "RestartRollout",
			Handler:    _RolloutService_RestartRollout_Handler,
		},
		{
			MethodName: "PromoteRollout",
			Handler:    _RolloutService_PromoteRollout_Handler,
		},
		{
			MethodName: "AbortRollout",
			Handler:    _RolloutService_AbortRollout_Handler,
		},
		{
			MethodName: "SetRolloutImage",
			Handler:    _RolloutService_SetRolloutImage_Handler,
		},
		{
			MethodName: "UndoRollout",
			Handler:    _RolloutService_UndoRollout_Handler,
		},
		{
			MethodName: "RetryRollout",
			Handler:    _RolloutService_RetryRollout_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _RolloutService_Version_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRolloutInfo",
			Handler:       _RolloutService_WatchRolloutInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchRolloutInfos",
			Handler:       _RolloutService_WatchRolloutInfos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/apiclient/rollout/rollout.proto",
}
